### ISSUE TITLE
掷色子可以让我变聪明吗 | Kvrmnks' blog

### ISSUE THREAD

**Issue by kvrmnks** [kvrmnks/kvrmnks.github.io#26]
https://kvrmnks.top/2021/11/14/2021/%E6%8E%B7%E8%89%B2%E5%AD%90%E5%8F%AF%E4%BB%A5%E8%AE%A9%E6%88%91%E5%8F%98%E8%81%AA%E6%98%8E%E5%90%97/

想试试看自己能不能写出民科一样的文风.

**Comment by SugarSBN** [comment]
小人潜水.jpg
